### ISSUE TITLE
VS1053 and MP3 METADATA

### ISSUE THREAD

**Issue by Tirguy** [baldram/ESP_VS1053_Library#30]
Hello !
Thank's a lot for this nice library : it's easy to use and work fine for me...
But i wondering if it was possible to add an option in order to access to the metadate from a mp3 stream ? 
I'd like to know witch song or music is playing on my board... It will permit me to put the song name on a screen for example...

Thank's again for help,
Thierry

**Comment by wmarkow** [comment]
I would vote for this as well, however not from MP3 but from web audio stream.

**Comment by baldram** [comment]
Hi @Tirguy thank you for comment and feedback. I'm glad you are were able to adopt the library in your project successfully. 
The library is kind of low level stuff to play the sound. To be honest I'm not sure whether this is a good place to implement handling of mp3 metadata. I would see it more in real-life implementation, like the web radio here: 
https://github.com/Edzelf/Esp-radio/blob/master/Esp_radio.ino
(please search for phrase "datamode == METADATA").
This is a "parent" project from where I extracted the essential part - the driver for VS1053. 
So it's also an example on how to do it.
Here is more clean example on how to handle ID3 tags: 
[Sparkfun-MP3-Player-Shield-Arduino](https://github.com/madsci1016/Sparkfun-MP3-Player-Shield-Arduino-Library/blob/f7dd1c2a6edf6a7d2ce7f31a14724627bfef3244/SFEMP3Shield/SFEMP3Shield.cpp) (search for "ID3").
I would also consider ready to use [PlaformIO library mp3tag](https://platformio.org/lib/show/4205/mp3tag). The problem is that it is designed for mbed framework, but the library is [very simple](https://os.mbed.com/users/christi_s/code/mp3tag/file/f07a503ce8fe/mp3tag.cpp/) and who knows, maybe it will go with ArduinoESP as well. 

So if there is a library to handle the ID3, now from some let's say music player project I would see it like following. We have a list of files read from SD card (with some SD Fat related library), then it extracts artist info (using some ID3 Tag library) to show the list of resources, further it shows the title when the song is being played with VS1053 library.

If for some reason the metadata handling can't be implemented in the higher level project (like web radio or audio player), this could be a part of VS1053 library. In conclusion, I would first look for the possibility of handling it from the higher level project.

What do you think?

**Comment by Tirguy** [comment]
OK, I'll think about how to implement this in my program, but I thought it could have been or should have been done on the lower layer, in the library.
Thank you for the answer,
Thierry

**Comment by baldram** [comment]
Thanks. 

> but I thought it could have been or should have been done on the lower layer, in the library

I agree, but as the VS1053 driver library is rather responsible only for playing the sound, it would be the other library. Eg. mentioned https://platformio.org/lib/show/4205/mp3tag (so maybe the idea would be to join this project, test it with ArduinoESP, add missing features, then use in your project - I think that would be a perfect solution).

Thank you for feedback and using ESP_VS1053_Library. I keep fingers crossed for your further steps. To be hones I would be personally interested in using [mp3tag](https://platformio.org/lib/show/4205/mp3tag) library in the future if it's ESP compatible.

Shall I close the ticket?

**Comment by Tirguy** [comment]
OK
You can close the ticket
