### ISSUE TITLE
Record audio

### ISSUE THREAD

**Issue by fredericplante** [baldram/ESP_VS1053_Library#35]
Beautiful work. do you have any idea how we could record or stream audio? I suddenly feel like those vs1053 could be turned into a walky-talkie

**Comment by baldram** [comment]
Hi @fredericplante, thank you for your question.
Do you use the library?
Have you been able to run it with your hardware? What ESP and VS1053 chip do you use (I mean manufacturer)?

Unfortunately the recording is not supported. That would be something like [this](https://github.com/adafruit/Adafruit_VS1053_Library/blob/master/examples/record_ogg/record_ogg.ino), but it would be necessary to extend the library code and add desired functionality. 
However, it has never been within my interests and I have no experience in this topic.
I've just updated README file. The issue is to be closed.
