### ISSUE TITLE
help with arduino board

### ISSUE THREAD

**Issue by hoahoctro** [baldram/ESP_VS1053_Library#36]
hi
I tested your lib with ESP8266 and it worked. But how about arduino uno ? Is there any lib suitable for it ?. 
I tried adafruit lib but it doesnt work
Hope your help, thanks

**Comment by baldram** [comment]
Hi @hoahoctro,
thanks for using the library. 
The main goal of this library is to support ESP boards. 
I also tried in the past the Adafruit's library and I had a lot of issues. So it was my motivation.
I was able to find a lot of examples for Arduino, but I was not interested in it. The ESP was my target platform.
I decided to create my own library. But as mentioned, the ESP oriented one.
That's why even the name of the library starts with "ESP_...." . 
Also as stated in [documentation](https://github.com/baldram/ESP_VS1053_Library#vs1053-library): "Designed specifically to work with the Espressif ESP8266 and ESP32 boards".

So this is the basic assumption that it won't support Arduino. However, it may work :) 
ESP specific things shouldn't cause any issues and be ignored by Arduino. You may let me know if it works. Just for curiosity. It won't change the basic assumption.
The library was ported from Arduino to ESP, but you may try the original maniacbug's library I refer in the [documentation](https://github.com/baldram/ESP_VS1053_Library#credits). 

Good luck.
