### ISSUE TITLE
Is it posible to show actual played song and artist?

### ISSUE THREAD

**Issue by thomasgoehler** [baldram/ESP_VS1053_Library#43]
it posible to show actual played song and artist?

**Comment by fabitom** [comment]
You need to made own buffer for that (more then 32 byte). Look handlebyte function in [https://github.com/Edzelf/Esp-radio/blob/master/Esp_radio.ino](https://github.com/Edzelf/Esp-radio/blob/master/Esp_radio.ino)

**Comment by baldram** [comment]
@fabitom Thank you for help in support. 
@thomasgoehler The `Esp_radio.ino` is a good example. 
So yes, it is possible. I see there also `showstreamtitle()` method, which could be a good example and start point. 
It will not be a part of this library since this is a functionality specific to a particular use case. 
I extracted only a core VS1053 driver from `Esp_radio.ino` to enable the possibility of doing various things. Web radio is one of many options. So handling of song and artist title is a part of your code.

Is this answer helpful, and can we close the issue?

**Comment by thomasgoehler** [comment]
Thank you for your fast response. Yes this was helpful and you can close
the thread.

Marcin Szałomski <notifications@github.com> schrieb am Do., 12. Dez. 2019,
21:55:

**Comment by baldram** [comment]
@thomasgoehler 
You're welcome.
Please also do not forget to give a star for a project if you like it ;-)
Thank you.
